<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>JustTooFast.CodeGen.SampleXml</AssemblyName>
    <RootNamespace>JustTooFast.CodeGen.SampleXml</RootNamespace>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/Core.csproj" />
    <ProjectReference Include="../Scaffolder.Cli/Scaffolder.Cli.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\SolutionInfo.cs" Link="Properties\SolutionInfo.cs" />
  </ItemGroup>

  <Target Name="GenerateSources" BeforeTargets="CoreCompile" Condition="'$(OS)' == 'Windows_NT' and '$(DesignTimeBuild)' != 'true'">
    <Exec Command="call $(ProjectDir)GenerateSources.bat &quot;$(ProjectDir)&quot; &quot;$(OutputPath)&quot; &quot;JustTooFast.CodeGen.SampleXml&quot;" />
  </Target>

  <Target Name="GenerateSources_Unix" BeforeTargets="CoreCompile" Condition="'$(OS)' == 'Unix' and '$(DesignTimeBuild)' != 'true'">
    <MakeDir Directories="$(ProjectDir)Output" />
    <Exec Command="bash &quot;$(ProjectDir)CleanupGenerated.sh&quot; &quot;$(ProjectDir)&quot;" />
    <Exec Command="dotnet run --no-build --project &quot;$(ProjectDir)../Scaffolder.Cli/Scaffolder.Cli.csproj&quot; -- &quot;$(ProjectDir)Input&quot; &quot;$(ProjectDir)Output&quot; &quot;JustTooFast.CodeGen.SampleXml&quot;" />
  </Target>

</Project>
