//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class AttributeBuilder
{
    private readonly AttributeInfo m_Attribute = new();

    public static implicit operator AttributeInfo(AttributeBuilder builder)
    {
        return builder.m_Attribute;
    }

    public static implicit operator AttributeDeclaration(AttributeBuilder builder)
    {
        return new AttributeDeclaration(builder.m_Attribute);
    }

    public AttributeBuilder WithName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentNullException(nameof(name));

        m_Attribute.Name = name;

        return this;
    }

    public AttributeBuilder WithValue(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentNullException(nameof(value));

        m_Attribute.Value = value;

        return this;
    }
}
