//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class ElementDeclaration
{
    private readonly ElementInfo m_Element;

    public ElementDeclaration(ElementInfo element)
    {
        m_Element = element ?? throw new ArgumentNullException(nameof(element));

        Validate();
    }

    private partial void Validate();
}
