//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class PrologDeclaration
{
    private readonly PrologInfo m_Prolog;

    public PrologDeclaration(PrologInfo prolog)
    {
        m_Prolog = prolog ?? throw new ArgumentNullException(nameof(prolog));

        Validate();
    }

    private partial void Validate();
}
