//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class PrologBuilder
{
    private readonly PrologInfo m_Prolog = new();

    public static implicit operator PrologInfo(PrologBuilder builder)
    {
        return builder.m_Prolog;
    }

    public static implicit operator PrologDeclaration(PrologBuilder builder)
    {
        return new PrologDeclaration(builder.m_Prolog);
    }

    public PrologBuilder WithXml(XmlInfo xml)
    {
        m_Prolog.Xml = xml ?? throw new ArgumentNullException(nameof(xml));

        return this;
    }

    public PrologBuilder WithXml(Func<XmlBuilder, XmlBuilder> builderFunc)
    {
        XmlBuilder builder = new();

        m_Prolog.Xml = builderFunc(builder);

        return this;
    }
}
