//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class RootElementDeclaration
{
    private readonly RootElementInfo m_RootElement;

    public RootElementDeclaration(RootElementInfo rootElement)
    {
        m_RootElement = rootElement ?? throw new ArgumentNullException(nameof(rootElement));

        Validate();
    }

    private partial void Validate();
}
