//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class RootElementBuilder
{
    private readonly RootElementInfo m_RootElement = new();

    public static implicit operator RootElementInfo(RootElementBuilder builder)
    {
        return builder.m_RootElement;
    }

    public static implicit operator RootElementDeclaration(RootElementBuilder builder)
    {
        return new RootElementDeclaration(builder.m_RootElement);
    }

    public RootElementBuilder WithName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentNullException(nameof(name));

        m_RootElement.Name = name;

        return this;
    }

    public RootElementBuilder WithAttribute(AttributeInfo attribute)
    {
        if (attribute == null)
            throw new ArgumentNullException(nameof(attribute));

        m_RootElement.Attributes.Add(attribute);

        return this;
    }

    public RootElementBuilder WithAttribute(Func<AttributeBuilder, AttributeBuilder> builderFunc)
    {
        AttributeBuilder builder = new();

        m_RootElement.Attributes.Add(builderFunc(builder));

        return this;
    }

    public RootElementBuilder WithAttributes(AttributeInfo[] attributes)
    {
        if (attributes == null)
            throw new ArgumentNullException(nameof(attributes));

        m_RootElement.Attributes.AddRange(attributes);

        return this;
    }

    public RootElementBuilder WithElement(ElementInfo element)
    {
        if (element == null)
            throw new ArgumentNullException(nameof(element));

        m_RootElement.Elements.Add(element);

        return this;
    }

    public RootElementBuilder WithElement(Func<ElementBuilder, ElementBuilder> builderFunc)
    {
        ElementBuilder builder = new();

        m_RootElement.Elements.Add(builderFunc(builder));

        return this;
    }

    public RootElementBuilder WithElements(ElementInfo[] elements)
    {
        if (elements == null)
            throw new ArgumentNullException(nameof(elements));

        m_RootElement.Elements.AddRange(elements);

        return this;
    }
}
