//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlBuilder
{
    private readonly XmlInfo m_Xml = new();

    public static implicit operator XmlInfo(XmlBuilder builder)
    {
        return builder.m_Xml;
    }

    public static implicit operator XmlDeclaration(XmlBuilder builder)
    {
        return new XmlDeclaration(builder.m_Xml);
    }

    public XmlBuilder WithEncoding(string encoding)
    {
        if (string.IsNullOrWhiteSpace(encoding))
            throw new ArgumentNullException(nameof(encoding));

        m_Xml.Encoding = encoding;

        return this;
    }

    public XmlBuilder WithStandalone(string standalone)
    {
        if (string.IsNullOrWhiteSpace(standalone))
            throw new ArgumentNullException(nameof(standalone));

        m_Xml.Standalone = standalone;

        return this;
    }
}
