//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlDeclaration
{
    private readonly XmlInfo m_Xml;

    public XmlDeclaration(XmlInfo xml)
    {
        m_Xml = xml ?? throw new ArgumentNullException(nameof(xml));

        Validate();
    }

    private partial void Validate();
}
