//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlFileInfo
{
    public PrologInfo Prolog
    { get; set; }

    public RootElementInfo RootElement
    { get; set; }
}
