//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlFileDeclaration
{
    private readonly XmlFileInfo m_XmlFile;

    public XmlFileDeclaration(XmlFileInfo xmlFile)
    {
        m_XmlFile = xmlFile ?? throw new ArgumentNullException(nameof(xmlFile));

        Validate();
    }

    private partial void Validate();
}
