//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlFileBuilder
{
    private readonly XmlFileInfo m_XmlFile = new();

    public static implicit operator XmlFileInfo(XmlFileBuilder builder)
    {
        return builder.m_XmlFile;
    }

    public static implicit operator XmlFileDeclaration(XmlFileBuilder builder)
    {
        return new XmlFileDeclaration(builder.m_XmlFile);
    }

    public XmlFileBuilder WithProlog(PrologInfo prolog)
    {
        m_XmlFile.Prolog = prolog ?? throw new ArgumentNullException(nameof(prolog));

        return this;
    }

    public XmlFileBuilder WithProlog(Func<PrologBuilder, PrologBuilder> builderFunc)
    {
        PrologBuilder builder = new();

        m_XmlFile.Prolog = builderFunc(builder);

        return this;
    }

    public XmlFileBuilder WithRootElement(RootElementInfo rootElement)
    {
        m_XmlFile.RootElement = rootElement ?? throw new ArgumentNullException(nameof(rootElement));

        return this;
    }

    public XmlFileBuilder WithRootElement(Func<RootElementBuilder, RootElementBuilder> builderFunc)
    {
        RootElementBuilder builder = new();

        m_XmlFile.RootElement = builderFunc(builder);

        return this;
    }
}
