//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlSnippetDeclaration
{
    private readonly XmlSnippetInfo m_XmlSnippet;

    public XmlSnippetDeclaration(XmlSnippetInfo xmlSnippet)
    {
        m_XmlSnippet = xmlSnippet ?? throw new ArgumentNullException(nameof(xmlSnippet));

        Validate();
    }

    private partial void Validate();
}
