//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.Xml;
public partial class XmlSnippetBuilder
{
    private readonly XmlSnippetInfo m_XmlSnippet = new();

    public static implicit operator XmlSnippetInfo(XmlSnippetBuilder builder)
    {
        return builder.m_XmlSnippet;
    }

    public static implicit operator XmlSnippetDeclaration(XmlSnippetBuilder builder)
    {
        return new XmlSnippetDeclaration(builder.m_XmlSnippet);
    }

    public XmlSnippetBuilder WithElement(ElementInfo element)
    {
        if (element == null)
            throw new ArgumentNullException(nameof(element));

        m_XmlSnippet.Elements.Add(element);

        return this;
    }

    public XmlSnippetBuilder WithElement(Func<ElementBuilder, ElementBuilder> builderFunc)
    {
        ElementBuilder builder = new();

        m_XmlSnippet.Elements.Add(builderFunc(builder));

        return this;
    }

    public XmlSnippetBuilder WithElements(ElementInfo[] elements)
    {
        if (elements == null)
            throw new ArgumentNullException(nameof(elements));

        m_XmlSnippet.Elements.AddRange(elements);

        return this;
    }
}
