//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace JustTooFast.CodeGen.SampleXml;
public partial class AttributeDeclaration
{
    private readonly AttributeInfo m_Attribute;

    public AttributeDeclaration(AttributeInfo attribute)
    {
        m_Attribute = attribute ?? throw new ArgumentNullException(nameof(attribute));

        Validate();
    }

    private partial void Validate();
}
