//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JustTooFast.CodeGen.SampleXml;
public partial class ElementBuilder
{
    private readonly ElementInfo m_Element = new();

    public static implicit operator ElementInfo(ElementBuilder builder)
    {
        return builder.m_Element;
    }

    public static implicit operator ElementDeclaration(ElementBuilder builder)
    {
        return new ElementDeclaration(builder.m_Element);
    }

    public ElementBuilder WithName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentNullException(nameof(name));

        m_Element.Name = name;

        return this;
    }

    public ElementBuilder WithText(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            throw new ArgumentNullException(nameof(text));

        m_Element.Text = text;

        return this;
    }

    public ElementBuilder WithAttribute(AttributeInfo attribute)
    {
        if (attribute == null)
            throw new ArgumentNullException(nameof(attribute));

        m_Element.Attributes.Add(attribute);

        return this;
    }

    public ElementBuilder WithAttribute(Func<AttributeBuilder, AttributeBuilder> builderFunc)
    {
        AttributeBuilder builder = new();

        m_Element.Attributes.Add(builderFunc(builder));

        return this;
    }

    public ElementBuilder WithAttributes(AttributeInfo[] attributes)
    {
        if (attributes == null)
            throw new ArgumentNullException(nameof(attributes));

        m_Element.Attributes.AddRange(attributes);

        return this;
    }

    public ElementBuilder WithElement(ElementInfo element)
    {
        if (element == null)
            throw new ArgumentNullException(nameof(element));

        m_Element.Elements.Add(element);

        return this;
    }

    public ElementBuilder WithElement(Func<ElementBuilder, ElementBuilder> builderFunc)
    {
        ElementBuilder builder = new();

        m_Element.Elements.Add(builderFunc(builder));

        return this;
    }

    public ElementBuilder WithElements(ElementInfo[] elements)
    {
        if (elements == null)
            throw new ArgumentNullException(nameof(elements));

        m_Element.Elements.AddRange(elements);

        return this;
    }
}
