//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace JustTooFast.CodeGen.SampleXml;
public partial class ElementInfo
{
    private readonly List<AttributeInfo> m_Attributes = new();
    private readonly List<ElementInfo> m_Elements = new();

    public string Name
    { get; set; }

    public string Text
    { get; set; }

    public List<AttributeInfo> Attributes
    {
        get { return m_Attributes; }
    }

    public List<ElementInfo> Elements
    {
        get { return m_Elements; }
    }
}
